name: Code Style Check (Pint)

on:
  push:
    branches:
      - '**'  # run on all branches
  pull_request:

jobs:
  pint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP with Pint
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, pint
          extensions: mbstring, xml, curl, zip

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run Laravel Pint in Test Mode (Check Only)
        run: vendor/bin/pint --test --verbose
